version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://root:example@mongo:27017
      - NODE_ENV= development
      - JWT_SECRET=dfjnfudniuerifnfgnfugngfiungiufng
    depends_on:
      - mongo
    command: npm run server
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-db:/data/

volumes:
  mongo-db:
